version: '3'
services:
  translator:
    build: ./translator
    depends_on:
#      - redis
      - db
    links:
      - db:db
    restart: always
    ports:
      - 3000:3000
#  redis:
#    image: redis:alpine
#    logging:
#      driver: "none"
#    restart: always
  db:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=privet
      - MYSQL_DATABASE=temp
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
