version: '3'
services:
  translator:
    build: ./translator
    depends_on:
#      - redis
      - db
    links:
      - db:db
    restart: always
#  redis:
#    image: redis:alpine
#    logging:
#      driver: "none"
#    restart: always
  db:
    image: mysql:5
    restart: always
 #   volumes:
#      - ./data/mysql:/var/lib/mysql
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
