version: '3'
services:
  translator:
    build:
      context: translator
      dockerfile: Dockerfile.development
    restart: on-failure
    ports:
      - 3000:3000
      - 127.0.0.1:9229:9229
    volumes:
       - ./translator/src:/root/app/src
    command: "watch"
    environment:
      NODE_ENV: development
      DB_URL: mysql://root:privatepass@db/translator?charset=utf8&timezone=UTC
  db:
    ports:
      - 3000:3000
    environment:
      - MYSQL_ROOT_PASSWORD=privatepass
      - MYSQL_DATABASE=translator
