version: '3'
services:
  translator:
    restart: always
    volumes:
      - ./logs:/root/app/logs
  environment:
    NODE_ENV: stage
    DB_URL: mysql://root:privatepass@db/translator?charset=utf8&timezone=UTC
#  redis:
#    image: redis:alpine
#    restart: always
  db:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=privatepass
      - MYSQL_DATABASE=translator
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
